apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-config
  namespace: scoolyn
data:
  APP_NAME: "Scoolyn"
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_URL: "https://scoolyn.example.com"
  LOG_CHANNEL: "stack"
  LOG_LEVEL: "error"
  DB_CONNECTION: "mysql"
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  DB_CONNECTION_TENANT: "mysql"
  BROADCAST_DRIVER: "log"
  CACHE_DRIVER: "file"
  QUEUE_CONNECTION: "sync"
  SESSION_DRIVER: "file"
  SESSION_LIFETIME: "120"